repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
    - id: nbdev_clean
    - id: nbdev_export

- repo: https://github.com/mwouts/jupytext
  rev: v1.14.7
  hooks:
    - id: jupytext
      args: [--sync, --pipe, black]
      additional_dependencies:
        - black==23.3.0

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      language_version: python3